FROM openjdk:11-jre-slim

# Set a working directory
WORKDIR /app

# Copy the Spring Boot JAR file to the container
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port (e.g., 8080)
EXPOSE 8000

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]